#!/bin/bash
# Orbi container entrypoint (community-maintained, Issue #264).
#
# Runs as root BEFORE systemd (PID 1) starts. It prepares the two state
# volumes and the official deployment inputs, then execs systemd — the
# `orbi-container-setup.service` oneshot then runs the official
# `orbi setup` inside the user session and the `orbi@.timer` takes over.
#
# Injected configuration (environment variables, never image layers):
#   GH_TOKEN          required. GitHub token with write access to the
#                     task pool. Written to /orbi/.orbi/env (the systemd
#                     EnvironmentFile) — gh and the git HTTPS credential
#                     helper read it from there at tick time.
#   ORBI_SOURCE_REPO  required. The task pool repo, `owner/repo`.
#   ORBI_ENV_<NAME>   optional, repeatable. Each one is written to
#                     /orbi/.orbi/env as <NAME>=<value> (e.g.
#                     ORBI_ENV_PROVIDER_API_KEY=... → PROVIDER_API_KEY=...)
#                     so a `pi_providers` file can reference it.
#   ORBI_BASE_BRANCH  optional. Delivery base branch for the generated
#                     config (default: main).
set -euo pipefail

msg() { printf 'docker-entrypoint: %s\n' "$*"; }
fail() { printf 'docker-entrypoint: %s\n' "$*" >&2; exit 1; }

# ---- 1. Injected configuration is validated before anything else -------
: "${GH_TOKEN:?GH_TOKEN is required (inject a GitHub token with -e GH_TOKEN=...)}"
: "${ORBI_SOURCE_REPO:?ORBI_SOURCE_REPO is required (the task pool repo, owner/repo)}"
[[ "$ORBI_SOURCE_REPO" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || fail \
  "invalid ORBI_SOURCE_REPO '$ORBI_SOURCE_REPO' (expected owner/repo)"
case "${ORBI_BASE_BRANCH:-main}" in
  ''|*[!A-Za-z0-9._/-]*) fail "invalid ORBI_BASE_BRANCH '${ORBI_BASE_BRANCH:-}'" ;;
esac
[[ "$GH_TOKEN" != *$'\n'* ]] || fail "GH_TOKEN contains a newline (env-file values must be single-line)"
for name in "${!ORBI_ENV_@}"; do
  [[ "${!name}" != *$'\n'* ]] || fail "$name contains a newline (env-file values must be single-line)"
done

# ---- 2. The unprivileged runtime user ----------------------------------
id orbi >/dev/null 2>&1 || useradd --uid 1000 --create-home --shell /bin/bash orbi
chown orbi:orbi /orbi /work

# ---- 3. Deploy home (/orbi): the orbi source checkout ------------------
# First start clones it; later starts reuse the volume as-is (the official
# ExecStartPre sync keeps it on the engine_source_track channel).
if [ ! -e /orbi/.git ]; then
  if [ -n "$(ls -A /orbi 2>/dev/null)" ]; then
    fail "/orbi is not a git checkout but is not empty — mount an empty volume or the orbi checkout itself"
  fi
  msg "cloning the orbi deploy home into /orbi"
  runuser -u orbi -- git clone https://github.com/orbi-build/orbi.git /orbi \
    || fail "cloning orbi-build/orbi failed (network/GitHub unreachable?)"
fi

# ---- 4. Generated config: never overwrite an existing one --------------
BASE_BRANCH="${ORBI_BASE_BRANCH:-main}"
if [ ! -f /orbi/orbi.toml ]; then
  msg "writing /orbi/orbi.toml (source repo $ORBI_SOURCE_REPO)"
  cat > /orbi/orbi.toml <<EOF
# Generated by the orbi docker entrypoint (3rd/docker). This file is
# yours: edit freely — the entrypoint never overwrites an existing
# config. The packaged example (src/orbi/example_config.toml) documents
# every
# field.
source_repos = ["$ORBI_SOURCE_REPO"]
repo_dir = "/work"
deploy_home = "/orbi"
workspace_root = "/work"
base_branch = "$BASE_BRANCH"
git_transport = "https"
engine_source_track = "release"
max_concurrency = 1
EOF
  chown orbi:orbi /orbi/orbi.toml
fi

# ---- 5. The deploy-home env file (the systemd EnvironmentFile) ---------
# Regenerated every start from the injected variables: the container env
# is the source of truth, the file is its persistence at tick time.
install -d -m 700 -o orbi -g orbi /orbi/.orbi
{
  echo "GH_TOKEN=$GH_TOKEN"
  for name in "${!ORBI_ENV_@}"; do
    printf '%s=%s\n' "${name#ORBI_ENV_}" "${!name}"
  done
} > /orbi/.orbi/env
chown orbi:orbi /orbi/.orbi/env
chmod 600 /orbi/.orbi/env

# ---- 6. Git HTTPS transport: route git credentials through gh ----------
# The official https transport contract (Issue #580): the gh credential
# helper supplies git credentials from GH_TOKEN; no SSH key anywhere.
# Configured BEFORE the task-pool clone so a private pool clones fine.
runuser -u orbi -- env HOME=/home/orbi GH_TOKEN="$GH_TOKEN" \
  gh auth setup-git >/dev/null \
  || fail "gh auth setup-git failed (is GH_TOKEN a valid token format?)"

# ---- 7. Delivery checkout (/work) --------------------------------------
# First start clones the task pool; a bind-mounted checkout is reused
# as-is. `orbi setup`'s checkout check validates it either way.
if [ ! -e /work/.git ]; then
  if [ -n "$(ls -A /work 2>/dev/null)" ]; then
    fail "/work is not a git checkout but is not empty — mount an empty volume, the task-pool checkout itself, or remove the stray files"
  fi
  msg "cloning the task pool into /work"
  runuser -u orbi -- env HOME=/home/orbi GH_TOKEN="$GH_TOKEN" \
    git clone "https://github.com/$ORBI_SOURCE_REPO.git" /work \
    || fail "cloning $ORBI_SOURCE_REPO failed (does the token grant read access?)"
fi
# Keep the runner's runtime state out of the checkout status, with the
# SAME local-exclude mechanism `orbi setup` uses for `.worktrees/`:
# the slot locks live in /work/.orbi/, and a rebuilt container re-runs
# the idempotent setup whose checkout check refuses a dirty checkout.
EXCLUDE=/work/.git/info/exclude
for line in ".orbi/" ".worktrees/"; do
  grep -qxF "$line" "$EXCLUDE" 2>/dev/null || echo "$line" >> "$EXCLUDE"
done
chown orbi:orbi "$EXCLUDE"

# ---- 8. The official editable CLI install ------------------------------
# Exactly the command the unit template's ExecStartPre self-heal runs;
# `orbi setup` verifies it and stays idempotent.
msg "installing the orbi CLI (editable uv tool install)"
runuser -u orbi -- env HOME=/home/orbi PATH="/home/orbi/.local/bin:/usr/local/bin:/usr/bin:/bin" \
  uv tool install --force --reinstall --editable --python python3 /orbi >/dev/null \
  || fail "the editable uv tool install of /orbi failed"

msg "handing over to systemd (setup runs as a oneshot; logs: docker logs -f)"
exec /usr/lib/systemd/systemd
