#!/bin/bash
# Orbi container entrypoint (community-maintained, Issue #264).
#
# Runs as root BEFORE systemd (PID 1) starts. It prepares the two state
# volumes and the official deployment inputs, then execs systemd — the
# `orbi-container-setup.service` oneshot then runs the official
# `orbi setup` inside the user session and the `orbi@.timer` takes over.
#
# Injected configuration (environment variables, never image layers):
#   GH_TOKEN          required. GitHub token with write access to the
#                     task pool. Written to /orbi/.orbi/env (the systemd
#                     EnvironmentFile) — gh and the git HTTPS credential
#                     helper read it from there at tick time.
#   ORBI_SOURCE_REPO  required. The task pool repo, `owner/repo`.
#   ORBI_ENV_<NAME>   optional, repeatable. Each one is written to
#                     /orbi/.orbi/env as <NAME>=<value> (e.g.
#                     ORBI_ENV_PROVIDER_API_KEY=... → PROVIDER_API_KEY=...)
#                     so a `pi_providers` file can reference it.
#   ORBI_BASE_BRANCH  optional. Delivery base branch for the generated
#                     config (default: main).
#   ORBI_PI_PROVIDER / ORBI_PI_MODEL / ORBI_PI_BASE_URL / ORBI_PI_API_KEY
#                     optional together. On a fresh start, configure the Pi
#                     provider and model; the key is written as PI_API_KEY.
#   ORBI_PI_API      optional API name (default: openai-completions).
#   ORBI_PI_CONTEXT_WINDOW / ORBI_PI_MAX_TOKENS optional model limits.
#                     Defaults: 128000 / 16384.
set -euo pipefail

# These defaults are the container paths. The overrides keep this script's
# subprocess tests isolated without changing the production path.
DEPLOY_HOME="${ORBI_DEPLOY_HOME:-/orbi}"
WORKSPACE="${ORBI_WORKSPACE:-/work}"
SYSTEMD_BIN="${ORBI_SYSTEMD_BIN:-/usr/lib/systemd/systemd}"
UV_BIN="${ORBI_UV_BIN:-uv}"
SETUP_LOG="${ORBI_SETUP_LOG:-/run/orbi-setup.log}"

msg() { printf 'docker-entrypoint: %s\n' "$*"; }
fail() { printf 'docker-entrypoint: %s\n' "$*" >&2; exit 1; }

# ---- 1. Injected configuration is validated before anything else -------
: "${GH_TOKEN:?GH_TOKEN is required (inject a GitHub token with -e GH_TOKEN=...)}"
: "${ORBI_SOURCE_REPO:?ORBI_SOURCE_REPO is required (the task pool repo, owner/repo)}"
[[ "$ORBI_SOURCE_REPO" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || fail \
  "invalid ORBI_SOURCE_REPO '$ORBI_SOURCE_REPO' (expected owner/repo)"
case "${ORBI_BASE_BRANCH:-main}" in
  ''|*[!A-Za-z0-9._/-]*) fail "invalid ORBI_BASE_BRANCH '${ORBI_BASE_BRANCH:-}'" ;;
esac
[[ "$GH_TOKEN" != *$'\n'* ]] || fail "GH_TOKEN contains a newline (env-file values must be single-line)"
for name in "${!ORBI_ENV_@}"; do
  [[ "${!name}" != *$'\n'* ]] || fail "$name contains a newline (env-file values must be single-line)"
done

pi_missing=()
for name in ORBI_PI_PROVIDER ORBI_PI_MODEL ORBI_PI_BASE_URL ORBI_PI_API_KEY; do
  [[ -n "${!name:-}" ]] || pi_missing+=("$name")
done
if (( ${#pi_missing[@]} > 0 && ${#pi_missing[@]} < 4 )); then
  fail "partial Pi provider configuration; missing ${pi_missing[*]}"
fi

# ---- 2. The unprivileged runtime user ----------------------------------
id orbi >/dev/null 2>&1 || useradd --uid 1000 --create-home --shell /bin/bash orbi
chown orbi:orbi "$DEPLOY_HOME" "$WORKSPACE"

# ---- 3. Deploy home (/orbi): the orbi source checkout ------------------
# First start clones it; later starts reuse the volume as-is (the official
# ExecStartPre sync keeps it on the engine_source_track channel).
if [ ! -e "$DEPLOY_HOME/.git" ]; then
  if [ -n "$(ls -A "$DEPLOY_HOME" 2>/dev/null)" ]; then
    fail "$DEPLOY_HOME is not a git checkout but is not empty — mount an empty volume or the orbi checkout itself"
  fi
  msg "cloning the orbi deploy home into $DEPLOY_HOME"
  runuser -u orbi -- git clone https://github.com/orbi-build/orbi.git "$DEPLOY_HOME" \
    || fail "cloning orbi-build/orbi failed (network/GitHub unreachable?)"
fi

# ---- 4. Generated config: never overwrite an existing one --------------
BASE_BRANCH="${ORBI_BASE_BRANCH:-main}"
if [ ! -f "$DEPLOY_HOME/orbi.toml" ]; then
  msg "writing $DEPLOY_HOME/orbi.toml (source repo $ORBI_SOURCE_REPO)"
  cat > "$DEPLOY_HOME/orbi.toml" <<EOF
# Generated by the orbi docker entrypoint (3rd/docker). This file is
# yours: edit freely — the entrypoint never overwrites an existing
# config. The packaged example (src/orbi/example_config.toml) documents
# every
# field.
source_repos = ["$ORBI_SOURCE_REPO"]
repo_dir = "/work"
deploy_home = "/orbi"
workspace_root = "/work"
base_branch = "$BASE_BRANCH"
git_transport = "https"
engine_source_track = "release"
max_concurrency = 1
EOF
  if (( ${#pi_missing[@]} == 0 )); then
    cat >> "$DEPLOY_HOME/orbi.toml" <<EOF
pi_providers = ".orbi/pi-providers.json"
pi_provider = "$ORBI_PI_PROVIDER"
pi_model = "$ORBI_PI_MODEL"
EOF
  fi
  chown orbi:orbi "$DEPLOY_HOME/orbi.toml"
fi

# ---- 5. The deploy-home env file (the systemd EnvironmentFile) ---------
# Regenerated every start from the injected variables: the container env
# is the source of truth, the file is its persistence at tick time.
install -d -m 700 -o orbi -g orbi "$DEPLOY_HOME/.orbi"
{
  echo "GH_TOKEN=$GH_TOKEN"
  for name in "${!ORBI_ENV_@}"; do
    printf '%s=%s\n' "${name#ORBI_ENV_}" "${!name}"
  done
  if (( ${#pi_missing[@]} == 0 )); then
    printf 'PI_API_KEY=%s\n' "$ORBI_PI_API_KEY"
  fi
} > "$DEPLOY_HOME/.orbi/env"
chown orbi:orbi "$DEPLOY_HOME/.orbi/env"
chmod 600 "$DEPLOY_HOME/.orbi/env"

if (( ${#pi_missing[@]} == 0 )); then
  if [ ! -e "$DEPLOY_HOME/.orbi/pi-providers.json" ]; then
    api="${ORBI_PI_API:-openai-completions}"
    context_window="${ORBI_PI_CONTEXT_WINDOW:-128000}"
    max_tokens="${ORBI_PI_MAX_TOKENS:-16384}"
    cat > "$DEPLOY_HOME/.orbi/pi-providers.json" <<EOF
{
  "providers": {
    "$ORBI_PI_PROVIDER": {
      "baseUrl": "$ORBI_PI_BASE_URL",
      "api": "$api",
      "apiKey": "\$PI_API_KEY",
      "models": [{
        "id": "$ORBI_PI_MODEL",
        "name": "$ORBI_PI_MODEL",
        "contextWindow": $context_window,
        "maxTokens": $max_tokens
      }]
    }
  }
}
EOF
    chown orbi:orbi "$DEPLOY_HOME/.orbi/pi-providers.json"
    msg "wrote Pi provider $ORBI_PI_PROVIDER for model $ORBI_PI_MODEL"
  fi
else
  msg "model delivery is not configured; set ORBI_PI_PROVIDER, ORBI_PI_MODEL, and ORBI_PI_BASE_URL"
fi

# ---- 6. Git HTTPS transport: route git credentials through gh ----------
# The official https transport contract (Issue #580): the gh credential
# helper supplies git credentials from GH_TOKEN; no SSH key anywhere.
# Configured BEFORE the task-pool clone so a private pool clones fine.
runuser -u orbi -- env HOME=/home/orbi GH_TOKEN="$GH_TOKEN" \
  gh auth setup-git >/dev/null \
  || fail "gh auth setup-git failed (is GH_TOKEN a valid token format?)"

# ---- 7. Delivery checkout (/work) --------------------------------------
# First start clones the task pool; a bind-mounted checkout is reused
# as-is. `orbi setup`'s checkout check validates it either way.
workspace_cloned=false
if [ ! -e "$WORKSPACE/.git" ]; then
  if [ -n "$(ls -A "$WORKSPACE" 2>/dev/null)" ]; then
    fail "$WORKSPACE is not a git checkout but is not empty — mount an empty volume, the task-pool checkout itself, or remove the stray files"
  fi
  msg "cloning the task pool into $WORKSPACE"
  runuser -u orbi -- env HOME=/home/orbi GH_TOKEN="$GH_TOKEN" \
    git clone "https://github.com/$ORBI_SOURCE_REPO.git" "$WORKSPACE" \
    || fail "cloning $ORBI_SOURCE_REPO failed (does the token grant read access?)"
  workspace_cloned=true
fi
# A repository can have a remote and fetched refs without having a commit
# checked out (for example after an interrupted clone). Fail here instead of
# exposing the raw `git rev-parse HEAD` error from `orbi setup`.
if ! runuser -u orbi -- git -C "$WORKSPACE" rev-parse HEAD >/dev/null 2>&1; then
  if $workspace_cloned; then
    fail "$ORBI_SOURCE_REPO has no commits — push an initial commit before starting Orbi"
  fi
  fail "$WORKSPACE must be a git checkout of $ORBI_SOURCE_REPO with a resolvable HEAD — mount the checkout with: docker run -v <path>:/work (or mount an empty volume so the task pool can be cloned)"
fi
# Keep the runner's runtime state out of the checkout status, with the
# SAME local-exclude mechanism `orbi setup` uses for `.worktrees/`:
# the slot locks live in /work/.orbi/, and a rebuilt container re-runs
# the idempotent setup whose checkout check refuses a dirty checkout.
EXCLUDE="$WORKSPACE/.git/info/exclude"
for line in ".orbi/" ".worktrees/"; do
  grep -qxF "$line" "$EXCLUDE" 2>/dev/null || echo "$line" >> "$EXCLUDE"
done
chown orbi:orbi "$EXCLUDE"

# ---- 8. The official editable CLI install ------------------------------
# Exactly the command the unit template's ExecStartPre self-heal runs;
# `orbi setup` verifies it and stays idempotent.
msg "installing the orbi CLI (editable uv tool install)"
runuser -u orbi -- env HOME=/home/orbi PATH="/home/orbi/.local/bin:/usr/local/bin:/usr/bin:/bin" \
  "$UV_BIN" tool install --force --reinstall --editable --python python3 "$DEPLOY_HOME" >/dev/null \
  || fail "the editable uv tool install of /orbi failed"

msg "handing over to systemd (setup runs as a oneshot; logs: docker logs -f orbi)"
# Keep a process holding the inherited Docker stdout pipe open: systemd
# reopens PID 1's stdio to /dev/null, so /proc/1/fd/1 is not usable here.
: > "$SETUP_LOG"
( exec tail -n +1 -F "$SETUP_LOG" ) &
exec "$SYSTEMD_BIN"
